name: 📦 Publish to PyPI on Tag

on:
  push:
    tags:
      - 'v*.*.*'  # es. v1.0.0

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    environment:
      name: publish
    permissions:
      id-token: write  # necessario per OIDC/trusted publishing
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install build tools
        run: pip install --upgrade build


      - name: Build package

        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1


